tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-secondary-fixed": "#1a1c1c",
                "on-tertiary-container": "#454545",
                "on-primary-fixed-variant": "#574500",
                "surface-container-lowest": "#0e0e0e",
                "surface-bright": "#393939",
                "secondary": "#c6c6c7",
                "surface-tint": "#e9c349",
                "surface": "#131313",
                "primary-container": "#d4af37",
                "outline-variant": "#4d4635",
                "surface-container": "#1f1f1f",
                "on-tertiary-fixed": "#1c1b1b",
                "primary-fixed-dim": "#e9c349",
                "on-secondary-container": "#b4b5b5",
                "secondary-fixed-dim": "#c6c6c7",
                "on-surface": "#e2e2e2",
                "error-container": "#93000a",
                "on-tertiary": "#313030",
                "surface-container-highest": "#353535",
                "on-primary": "#3c2f00",
                "tertiary-fixed": "#e5e2e1",
                "secondary-container": "#454747",
                "outline": "#99907c",
                "inverse-surface": "#e2e2e2",
                "tertiary-fixed-dim": "#c8c6c5",
                "error": "#ffb4ab",
                "surface-dim": "#131313",
                "primary-fixed": "#ffe088",
                "tertiary-container": "#b5b2b2",
                "secondary-fixed": "#e2e2e2",
                "on-background": "#e2e2e2",
                "surface-container-high": "#2a2a2a",
                "inverse-primary": "#735c00",
                "surface-variant": "#353535",
                "on-primary-fixed": "#241a00",
                "background": "#131313",
                "surface-container-low": "#1b1b1b",
                "inverse-on-surface": "#303030",
                "primary": "#f2ca50",
                "on-surface-variant": "#d0c5af",
                "on-tertiary-fixed-variant": "#474646",
                "tertiary": "#d0cecd",
                "on-primary-container": "#554300",
                "on-secondary-fixed-variant": "#454747",
                "on-secondary": "#2f3131",
                "on-error-container": "#ffdad6",
                "on-error": "#690005"
            },
            "borderRadius": {
                "sm": "0.25rem",
                "DEFAULT": "0.5rem",
                "md": "0.75rem",
                "lg": "1rem",
                "xl": "1.5rem",
                "full": "9999px"
            },
            "spacing": {
                "gutter": "24px",
                "section-gap": "120px",
                "margin-desktop": "80px",
                "base": "4px",
                "margin-mobile": "20px",
                "container-max": "1440px"
            },
            "fontFamily": {
                "label-caps": ["Sora"],
                "display-hero-mobile": ["Playfair Display"],
                "body-md": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"],
                "display-hero": ["Playfair Display"],
                "headline-lg-mobile": ["Playfair Display"],
                "headline-md": ["Sora"],
                "headline-lg": ["Playfair Display"],
                "button-text": ["Sora"]
            },
            "fontSize": {
                "label-caps": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "700"}],
                "display-hero-mobile": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "display-hero": ["84px", {"lineHeight": "92px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "0.02em", "fontWeight": "600"}],
                "headline-lg": ["48px", {"lineHeight": "56px", "fontWeight": "600"}],
                "button-text": ["16px", {"lineHeight": "20px", "fontWeight": "600"}]
            }
        },
    },
}
